# This is a basic workflow to help you get started with Actions

name: Name of 2nd workflow with modified workflow template

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # env is where we declare the variables. In this case, name is a variable with the value of Arr and can only be accessed on build job level
    env:
      # name here is the variable with a value of Arr
      name: Arr
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello $name!
  
  # This is the 2nd job
  pull_requests_only:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # if statement; github is an special object to get info about the current environment
    if: github.event_name == 'pull_request'
    # needs meeans that this job will only run after the previous job is finished
    needs: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
